CREATE TABLE newssrc
(
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) DEFAULT '',
  LOCATION VARCHAR(2048) DEFAULT ''
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE news
(
  ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  TITLE TEXT,
  CONTENT MEDIUMTEXT,
  APPEND_TIMESTAMP TIMESTAMP,
  SOURCE_ID INT NOT NULL,
  FOREIGN KEY (SOURCE_ID) REFERENCES newssrc(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
